# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#5d5d5d", bold = true, underline = true }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#eaeaea", bold = true, italic = true, underline = true }
find_position = { fg = "#9d9d9d", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#778777", bg = "#778777" }
marker_cut = { fg = "#b07878", bg = "#b07878" }
marker_marked = { fg = "#d6caab", bg = "#d6caab" }
marker_selected = { fg = "#eaeaea", bg = "#eaeaea" }

# Count
count_copied = { fg = "#1e1e1e", bg = "#778777" }
count_cut = { fg = "#1e1e1e", bg = "#b07878" }
count_selected = { fg = "#1e1e1e", bg = "#eaeaea" }

# Border
border_symbol = "│"
border_style = { fg = "#5d5d5d" }

# Symlink
symlink_target = { italic = true }

# Highlighting
syntect_theme = ""

# : }}}

# : Tabs {{{

[tabs]
active = { bg = "#1e1e1e", bold = true }
inactive = { fg = "#1e1e1e", bg = "#686868" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}

# : Mode {{{

[mode]

normal_main = { fg = "#1e1e1e", bg = "#686868", bold = true }
normal_alt = { fg = "#1e1e1e", bg = "#686868" }

# Select mode
select_main = { fg = "#1e1e1e", bg = "#eaeaea", bold = true }
select_alt = { fg = "#1e1e1e", bg = "#eaeaea" }

# Unset mode
unset_main = { fg = "#1e1e1e", bg = "#c8a492", bold = true }
unset_alt = { fg = "#1e1e1e", bg = "#c8a492" }

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#353535", bg = "#353535" }

# Progress
progress_label = { fg = "#cccccc", bold = true }
progress_normal = { fg = "#686868", bg = "#353535" }
progress_error = { fg = "#b07878", bg = "#353535" }

# Permissions
perm_sep = { fg = "#5d5d5d" }
perm_type = { fg = "#7d96ad" }
perm_read = { fg = "#d6caab" }
perm_write = { fg = "#b07878" }
perm_exec = { fg = "#778777" }

# : }}}


# : Which {{{

[which]
cols = 3
mask = { bg = "#2a2a2a" }
cand = { fg = "#9bb09b" }
rest = { fg = "#707070" }
desc = { fg = "#9d9d9d" }
separator = "  "
separator_style = { fg = "#414141" }

# : }}}


# : Confirmation {{{

[confirm]
border = { fg = "#5d5d5d" }
title = { fg = "#9d9d9d" }
content = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}
btn_labels = ["  [Y]es  ", "  [N]o  "]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#5d5d5d" }
title = { fg = "#9d9d9d" }

# Table
tbl_col = { fg = "#5d5d5d" }
tbl_cell = { fg = "#707070", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info = { fg = "#778777" }
title_warn = { fg = "#c8a492" }
title_error = { fg = "#b07878" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border = { fg = "#5d5d5d" }
active = { fg = "#9d9d9d", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#5d5d5d" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#5d5d5d" }
active = { reversed = true }
inactive = {}

# Icons
icon_file = ""
icon_folder = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#5d5d5d" }
title = {}
hovered = { fg = "#9d9d9d", underline = true }

# : }}}


# : Help {{{

[help]
on = { fg = "#9bb09b" }
run = { fg = "#9d9d9d" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#353535", bg = "#b3b3b3" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#5d5d5d" },

  # Media
  { mime = "{audio,video}/*", fg = "#5d5d5d" },

  # Archives
  { mime = "application/*zip", fg = "#707070" },
  { mime = "application/{tar,bzip*,7z-compressed,xz,rar}", fg = "#707070" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#686868" },

  # Empty files
  { mime = "inode/empty", fg = "#b07878" },

  # Special files
  { name = "*", is = "orphan", bg = "#b07878" },
  { name = "*", is = "exec", fg = "#dcdcdc" },

  # Dummy files
  { name = "*", is = "dummy", bg = "#b07878" },
  { name = "*/", is = "dummy", bg = "#b07878" },

  # Fallback
  { name = "*", fg = "#7f7f7f" },
  { name = "*/", fg = "#7f7f7f" },
]

# : }}}
